#+TITLE: A Tree-Sitter parser for Org Mode nodes
#+ARCHIVE: ./docs/plans/ROADMAP_ARCHIVE.org::

* Bugfixes
** DONE Duration token edge case
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-04-06 Mon 00:26]
:END:

#+begin_example
,* A
:PROPERTIES:
:END:
,** B
,* C
:PROPERTIES:
:END:
,** D
,* E
:LOGBOOK:
- State "DONE"       from "TODO"       [2014-01-16 czw 20:31]
:END:
#+end_example

The node tree lists =first_line: (plain_text (MISSING "_DURATION_token1")))= at the end of the line.

** DONE Strikethrough in tables
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-04-06 Mon 01:05]
:END:
#+begin_example
| /lxml/        | Python     | =BSD-3-Clause= | [[https://lxml.de]]                   |
| ~pest~        | Rust       | =MIT / Apache= | [[https://pest.rs]]                   |
| +ANTLR 3+     | Java       | =BSD=          | _deprecated_ — use ANTLR 4            |
| *ANTLR 4*     | Java/many  | =BSD-3-Clause= | [[https://www.antlr.org]]             |
| /Menhir/      | OCaml      | =LGPL-2=       | [[https://gallium.inria.fr/~fpottier/menhir/]] |
#+end_example

The strikethrough on line 3 spans until the =|= character even though there's a =+= character that should end the strikethrough. 

** DONE Timestamp delay/repeater marks are missing the value
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-05-12 Tue 20:30]
:END:
Here are three examples with different kinds of repeaters on their timestamps. In all cases, the values are not actually parsed, making it less useful:

#+begin_example
,* Delay
DEADLINE: <2025-12-07 nie -5d>

,* Repeater
SCHEDULED: <2025-12-11 czw +3d>

,* Repeater with cap
SCHEDULED: <2025-12-11 czw +1m/3m>
#+end_example

I'd like the value to be available on the parse tree. Please make sure to expose all the components of the timestamp in the parse tree as named nodes.

* Pipeline improvements
** DONE Check.py should check for missing tokens as well as error nodes.
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-04-06 Mon 00:54]
:END:


* Next
** NPM publishing
Add release jobs that publish to NPM.

** Rust, Go, Swift bindings
- Release to crates.io, etc
